version: 2

run:
  timeout: 3m
  tests: True

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosec
  disable:
    - gocyclo
    - funlen

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    colored-line-number: {}
